### ISSUE TITLE
Network location provider at 'https://www.googleapis.com/' : No response received.

### ISSUE THREAD

**Issue by jakeauyeung** [ninjatronic/ngGeolocation#11]
error: Network location provider at 'https://www.googleapis.com/' : No response received.

**Comment by hemangshah** [comment]
@jakeauyeung have you ever found any solution to this? I am getting the same error in ionic-angular project with Geolocation plugin of googlemapsapi

**Comment by Santosh008** [comment]
Hi,
 Getting the same issue when calling navigator.geolocation.getCurrentPosition in angular project but this happens only in chrome

**Comment by hemangshah** [comment]
@Santosh008 for me this only happens on Windows electron app? Are you able to achieve this on windows electron app?
